### ISSUE TITLE
Pathnames by `Tar.create` differ from pathnames by command line utility

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/Tar.jl#21]
The following observation
```julia
julia> Tar.create("ball", "t3.tar")
"t3.tar"
julia> Tar.list("t3.tar")
3-element Array{Tar.Header,1}:
 Tar.Header("a.dat", :file, 0o644, 10, "")
 Tar.Header("empty/", :directory, 0o755, 0, "")
 Tar.Header("sub/a.dat", :file, 0o644, 10, "")

shell> tar -cf t4.tar ball
julia> Tar.list("t4.tar")
5-element Array{Tar.Header,1}:
 Tar.Header("ball/", :directory, 0o755, 0, "")
 Tar.Header("ball/sub/", :directory, 0o755, 0, "")
 Tar.Header("ball/sub/a.dat", :file, 0o644, 10, "")
 Tar.Header("ball/a.dat", :file, 0o644, 10, "")
 Tar.Header("ball/empty/", :directory, 0o755, 0, "")
```
raises two questions:
1. why don't the pathnames of `Tar.create` contain the outermost directory name as tar's does?
2. why are the non-empty directory entries missing (while their permission bits might be important)?

**Comment by StefanKarpinski** [comment]
Correct. Both are by design.

1. The path to the data you are recording is not part of the data. If you want to include that prefix then it is part of the data and should be inside of the tarball. This is one of the reasons it’s hard to use `tar` to just record the contents of a directory the way `git` or any other version control systems do. Even when you coax `tar` into doing it, you end up with an unnecessary `./` prefix on every tarball entry because it _wants_ to care about where things live.

2. `Tar` doesn’t record or restore any data about directories, including permissions, except that they exist. This is discussed extensively in the README. So everything it needs to know about non-empty directories is implied just by having something in them. There are currently no options to record or restore permission. If such options are added then it would have to record entries for directories with non-default permissions.

**Comment by KlausC** [comment]
I was just worried about seamless interoperability between `Tar` and `tar`. Maybe that should be noted in README.

**Comment by StefanKarpinski** [comment]
What's the interoperability issue? Tar can consume tarballs created by `tar` and vice versa. Let me know if you can think of a way to clarify further in the README that they do not have the same API and are not intended to produce the same TAR files (if they did, there would be little point in this package).

**Comment by KlausC** [comment]
for example:
`Tar.create("dirpath", "x.tar")` is roughly equivalent to `tar -f x.tar -C dirpath -c $(cd dirpath; ls -A)`.
`Tar.extract("x.tar", "dirpath") is simlar to `mkdir -p dirpath; tar -f x.tar -C dirpath`

**Comment by StefanKarpinski** [comment]
You mean to add that to the docs as an example?

**Comment by KlausC** [comment]
Yes, I thought so.
> (if they did, there would be little point in this package).

I found this package extremely valuable, because I wanted to read the contents of individual elements of (compressed) tar archives without have to extract them to disk. I saw that the `Tar.read_header` did already most of the job. In the meanwhile I made this package [TarIterators.jl](https://github.com/KlausC/TarIterators.jl) which extends `Tar` in the way I need.

**Comment by StefanKarpinski** [comment]
Oh, very cool! Once that settles down and you're happy with the way it works, we should take a look at rolling it into the main `Tar` package if that makes sense to you, although it's a pretty clean extension the way it is. I would also be open to adding other metadata to the `Header` construct that can be extracted from the header stream like permissions and [mca]times, even if `Tar` itself doesn't use those fields by default. After all, extracting them is quite easy and we're already doing most of the work, so why not?
